### ISSUE TITLE
Dosen't send interrupt signal while the second time file change

### ISSUE THREAD

**Issue by ohano** [air-verse/air#129]
After I boot the Air , I modify the files which are under watched, it can send a interrupt signal normally~
And when I modify the file again, air wouldn't send a interrupt signal any more~
Both Mac and Linux~

kill_delay = 5000 # ms

**Comment by makiuchi-d** [comment]
This is a serious bug of the flag `Engine.binRunning`.

At the first time to run the process, `e.binRunning` becomes true in the func `e.runBin()`.
https://github.com/cosmtrek/air/blob/v1.27.3/runner/engine.go#L399

When the file modified, in the loop of the func `e.start()`, the message is sent to the channel `e.binStopCh` to stop the old process, and `buildRun()` is called to build and start the new process (`e.runBin()` is called in this method).
https://github.com/cosmtrek/air/blob/v1.27.3/runner/engine.go#L320-L325

The message is received from `e.binStopCh` at line 408, the func `e.killCmd()` is called.
The func `e.killCmd()` takes more than `kill_delay` milliseconds when `send_interrupt` is true.
https://github.com/cosmtrek/air/blob/v1.27.3/runner/engine.go#L408-L416
https://github.com/cosmtrek/air/blob/v1.27.3/runner/util_linux.go#L20

In parallel with that, the new process is started and `e.binRunning` becomes true.

At `kill_delay` milliseconds later, the func `killCmd()` completes and `e.binRunning` becomes false.
https://github.com/cosmtrek/air/blob/v1.27.3/runner/engine.go#L426

As the result, the flag `e.binRunning` is false, even though the process is running.
It means that the message will not be sent to the channel `e.binStopCh` when the file modified.
Therefore, the process cannot be stopped.

The incidence of this bug increases when the `send_interrupt` is true, but it can occur otherwise.

**Comment by xiantang** [comment]
> https://github.com/cosmtrek/air/blob/v1.27.3/runner/engine.go#L399

hello. could you provide  the Minimum reproducible sample?

**Comment by makiuchi-d** [comment]
main.go:
```
package main

import "time"

func main() {
	time.Sleep(time.Minute)
}
```

air.toml (copied from air_example.toml and made `send_interrupt` true):
```
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ."
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary.
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = []
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
```

start air:
```
$ air -d -c air.toml
```

watch processes:
```
$ watch -n1 pstree -pa `ps u|awk '/[a]ir.toml/{print $2}'`
```

modify file:
```
$ echo >> main.go
```

It can be observed that the process does not end every two times of file modification.

**Comment by ryanolds-drizly** [comment]
I've seen similar issues, but its not reloading because there is a race condition when two builds fail after a successful build and run. Its possible for `e.binStopCh <- true` to block and hold the lock. This prevents `e.binRunning = false` in the other lock from bring run because its waiting for the mutex, resulting in a dead lock.
